CREATE SCHEMA GESTAO_ATL
GO

CREATE TABLE GESTAO_ATL.PROFESSOR (
    Numero_Funcionario INT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    CC VARCHAR(20) UNIQUE,
    Data_nascimento DATE,
    Telefone VARCHAR(20),
    Email VARCHAR(100),
    Morada VARCHAR(255)
);

CREATE TABLE GESTAO_ATL.TURMA (
    Identificador VARCHAR(50) PRIMARY KEY,
    Ano_Lectivo VARCHAR(20),
    Classe VARCHAR(20),
    Designacao VARCHAR(100),
    Max_Alunos INT,
    Professor_FK INT,
    FOREIGN KEY (Professor_FK) REFERENCES GESTAO_ATL.PROFESSOR(Numero_Funcionario)
);

CREATE TABLE GESTAO_ATL.CONTACTO (
    CC VARCHAR(20) PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    Relacao VARCHAR(50),
    Data_nascimento DATE,
    Telefone VARCHAR(20),
    Email VARCHAR(100),
    Morada VARCHAR(255)
);

CREATE TABLE GESTAO_ATL.ALUNO (
    CC VARCHAR(20) PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    Data_nascimento DATE,
    Morada VARCHAR(255),
    Turma_FK VARCHAR(50),
    Encarregado_FK VARCHAR(20),
    FOREIGN KEY (Turma_FK) REFERENCES GESTAO_ATL.TURMA(Identificador),
    FOREIGN KEY (Encarregado_FK) REFERENCES GESTAO_ATL.CONTACTO(CC)
);

CREATE TABLE GESTAO_ATL.AUTORIZADO (
    CC_Contacto_FK VARCHAR(20),
    CC_Aluno_FK VARCHAR(20),
    PRIMARY KEY (CC_Contacto_FK, CC_Aluno_FK),
    FOREIGN KEY (CC_Contacto_FK) REFERENCES GESTAO_ATL.CONTACTO(CC),
    FOREIGN KEY (CC_Aluno_FK) REFERENCES GESTAO_ATL.ALUNO(CC)
);

CREATE TABLE GESTAO_ATL.ATIVIDADE (
    Identificador INT PRIMARY KEY,
    Designacao VARCHAR(150) NOT NULL,
    Custo DECIMAL(10, 2)
);

CREATE TABLE GESTAO_ATL.DISPONIVEL (
    Turma_FK VARCHAR(50),
    Atividade_FK INT,
    PRIMARY KEY (Turma_FK, Atividade_FK),
    FOREIGN KEY (Turma_FK) REFERENCES GESTAO_ATL.TURMA(Identificador),
    FOREIGN KEY (Atividade_FK) REFERENCES GESTAO_ATL.ATIVIDADE(Identificador)
);

CREATE TABLE GESTAO_ATL.PARTICIPA (
    Aluno_FK VARCHAR(20),
    Atividade_FK INT,
    PRIMARY KEY (Aluno_FK, Atividade_FK),
    FOREIGN KEY (Aluno_FK) REFERENCES GESTAO_ATL.ALUNO(CC),
    FOREIGN KEY (Atividade_FK) REFERENCES GESTAO_ATL.ATIVIDADE(Identificador)
);


